export const swaggerOptions = {
    swaggerDefinition: {
      openapi: '3.0.0',
      info: {
        title: 'Financial Health Check API',
        version: '1.0.0',
        description: 'API documentation for Financial Health Check application',
      },
      components: {
        schemas: {
          EducationPlan: {
            type: 'object',
            properties: {
              id: { type: 'string' },
              user_params: { type: 'string' },
              nickname: { type: 'string' },
              age: { type: 'string' },
              levelOfeducation: { type: 'string' },
              typeOfeducation: { type: 'string' },
              yearsOfeducation: { type: 'string' },
              inflationRate: { type: 'string' },
              deposit: { type: 'string' },
              insuranceFund: { type: 'string' },
              otherAssets: { type: 'string' },
              createdAt: { type: 'string', format: 'date-time' },
              updatedAt: { type: 'string', format: 'date-time' },
            },
          },
          ProtectionPlan: {
            type: 'object',
            properties: {
              id: { type: 'string' },
              user_params: { type: 'string' },
              nickname: { type: 'string' },
              age: { type: 'string' },
              initialMonthlyExpense: { type: 'string' },
              numberOfYears: { type: 'string' },
              adjustedYearlyExpenses: { type: 'string' },
              inflationRate: { type: 'string' },
              homePayments: { type: 'string' },
              carPayments: { type: 'string' },
              otherDebts: { type: 'string' },
              bankDeposit: { type: 'string' },
              lifeInsuranceFund: { type: 'string' },
              otherAssets: { type: 'string' },
              createdAt: { type: 'string', format: 'date-time' },
              updatedAt: { type: 'string', format: 'date-time' },
            },
          },
          Importance: {
            type: 'object',
            properties: {
              id: { type: 'string' },
              user_params: { type: 'string' },
              nickname: { type: 'string' },
              age: { type: 'string' },
              protectionPlanOrder: { type: 'string' },
              healthPlanOrder: { type: 'string' },
              retirementPlanOrder: { type: 'string' },
              educationPlanOrder: { type: 'string' },
              createdAt: { type: 'string', format: 'date-time' },
              updatedAt: { type: 'string', format: 'date-time' },
            },
          },
          User: {
            type: 'object',
            properties: {
              id: { type: 'string' },
              user_params: { type: 'string' },
              createdAt: { type: 'string', format: 'date-time' },
              updatedAt: { type: 'string', format: 'date-time' },
            },
          },
          HealthPlan: {
            type: 'object',
            properties: {
              id: { type: 'string' },
              user_params: { type: 'string' },
              nickname: { type: 'string' },
              age: { type: 'string' },
              hospitals: { type: 'string' },
              dailyCompensationFromWelfare: { type: 'string' },
              treatingSeriousIllness: { type: 'string' },
              emergencyCosts: { type: 'string' },
              annualTreatment: { type: 'string' },
              roomFeeFromCompany: { type: 'string' },
              dailyCompensationFromCompany: { type: 'string' },
              treatingSeriousIllnessFromCompany: { type: 'string' },
              emergencyCostsFromCompany: { type: 'string' },
              annualTreatmentFromCompany: { type: 'string' },
              createdAt: { type: 'string', format: 'date-time' },
              updatedAt: { type: 'string', format: 'date-time' },
            },
          },
          RetirementPlan: {
            type: 'object',
            properties: {
              id: { type: 'string' },
              user_params: { type: 'string' },
              nickname: { type: 'string' },
              age: { type: 'string' },
              livingCosts: { type: 'string' },
              houseCosts: { type: 'string' },
              internetCosts: { type: 'string' },
              clothingCosts: { type: 'string' },
              medicalCosts: { type: 'string' },
              otherCosts: { type: 'string' },
              retireAge: { type: 'string' },
              lifExpectancy: { type: 'string' },
              inflationRate: { type: 'string' },
              deposit: { type: 'string' },
              insuranceFund: { type: 'string' },
              otherAssets: { type: 'string' },
              createdAt: { type: 'string', format: 'date-time' },
              updatedAt: { type: 'string', format: 'date-time' },
            },
          },
        },
      },
    },
    apis: ['./routes/*.js'],
  };